server {
    listen 80;

    client_max_body_size 50M;

    location /analyze {
        proxy_pass http://backend-service:8000;
    }

    location /evaluation {
        proxy_pass http://backend-service:8000;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
